# Generated by Django 4.2.5 on 2023-10-06 05:51

from django.db import migrations, models
import qrgenerator.models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.ImageField(upload_to=qrgenerator.models.QRCode.path_to_qr),
        ),
    ]
